# Use root/example as user/password credentials
version: '3.9'

services:
  mongodb:
    container_name: mongo-books
    image: mongo
    restart: always
    networks:
      - mongo-compose-network
    ports:
      - 27017:27017
    volumes:
      - D:\data\books-mongodb:/data/db
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: admin
      #MONGO_INITDB_ROOT_PASSWORD: pass
    #command: mongod --port 27017 --auth
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express-books
    restart: always
    depends_on:
      - mongodb
    networks:
      - mongo-compose-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-books
      #ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      #ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      #ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass

networks:
  mongo-compose-network:
    driver: bridge